{
  inputs = {
    nixpkgs.url = "github:michaeladler/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils, nur }:

    {
      overlay = import ./overlay.nix;
    } // (flake-utils.lib.eachSystem [ "x86_64-linux" ] (system:

      let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ self.overlay ];
          config.allowUnfree = true;
        };

      in
      {

        devShell = with pkgs;
          mkShell {
            nativeBuildInputs = [ update-nix-fetchgit ];
          };

        # we have to use legacyPackages for sets of derivations (trees)
        # the package names generated by flattenTree cause issues when using them,
        # so they are re-exported here
        # https://github.com/numtide/flake-utils/pull/29#issuecomment-817652939
        legacyPackages = {
          inherit (pkgs)
            firefoxAddons
            extraLuaJITPackages
            ;
          linux = {
            zen = pkgs.linuxPackages_zen.kernel;
            lqx = pkgs.linuxPackages_lqx.kernel;
            vanilla = pkgs.linuxPackages_6_0.kernel;
          };
          nvidia = {
            zen = pkgs.linuxPackages_zen.nvidiaPackages.latest;
            lqx = pkgs.linuxPackages_lqx.nvidiaPackages.latest;
            vanilla = pkgs.linuxPackages_6_0.nvidiaPackages.latest;
          };
          cpupower = {
            zen = pkgs.linuxPackages_zen.cpupower;
            lqx = pkgs.linuxPackages_lqx.cpupower;
            vanilla = pkgs.linuxPackages_6_0.cpupower;
          };
        };

        packages = flake-utils.lib.flattenTree {
          inherit (pkgs)
            age-plugin-yubikey
            brave
            btrfs-du
            btrfs-list
            chromium-browserpass
            chromium-floccus
            chyle
            cinclude2dot
            clang-format-diff
            criterion
            czmod
            efibootguard
            fmtlog
            fstabfmt
            fzy-lua-native
            git-hours
            go-crx3
            go-mod-outdated
            kas-container
            libubootenv
            luaprompt
            nix-direnv
            pandoc
            qmarkdown
            sbkeys
            skipcpio
            sscep
            sumneko-lua-language-server
            thinkfan
            tlpui
            vcalendar-filter
            zinit
            zoxide
            pam-fprint-grosshack
            srandrd
            git-latest
            git-buildpackage
            chromium-vimium
            chromium-xbrowsersync
            msktutil
            notmuch-mailmover
            bed
            clipboard
            waybar-hyprland

            # fill cache
            astroid
            stylua
            cargo-generate
            marksman
            zstd-optimized

            ;

          zen_nvidia_open = pkgs.linuxPackages_zen.nvidiaPackages.latest.open;
        };

        defaultPackage = pkgs.hello;

      }));
}
