{
  description = "My NUR";

  #inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  inputs.nixpkgs.url = "github:michaeladler/nixpkgs/nixos-unstable";
  inputs.flake-utils.url = "github:numtide/flake-utils";

  inputs.nur.url = github:nix-community/NUR;

  inputs.rnix-lsp-src = {
    url = "github:nix-community/rnix-lsp";
    inputs.nixpkgs.follows = "nixpkgs";
  };
  inputs.naersk = {
    url = "github:nmattia/naersk";
  };

  outputs = { self, nixpkgs, flake-utils, nur, naersk, rnix-lsp-src }:

    {
      overlay = import ./overlay.nix;
    } // (flake-utils.lib.eachSystem [ "x86_64-linux" ] (system:

      let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ self.overlay ];
          config.allowUnfree = true;
        };
        nurPkgs = import nixpkgs {
          inherit system;
          overlays = [ nur.overlay ];
        };
        naersk-lib = naersk.lib."${system}";

      in
      {

        # we have to use legacyPackages for sets of derivations (trees)
        # the package names generated by flattenTree cause issues when using them,
        # so they are re-exported here
        # https://github.com/numtide/flake-utils/pull/29#issuecomment-817652939
        legacyPackages = {
          inherit (pkgs)
            firefoxAddons
            ;
        };

        packages = flake-utils.lib.flattenTree {
          inherit (rnix-lsp-src.packages.x86_64-linux) rnix-lsp;
          inherit (pkgs)
            brave
            btrfs-du
            btrfs-list
            ccls
            cinclude2dot
            clang-format-diff
            dotdrop
            efibootguard
            firefox-bin
            fmt_8
            fmtlog
            fstabfmt
            fzy-lua-native
            git-hours
            go-crx3
            go-mod-outdated
            goofys
            handlr
            i3-gaps
            kas-container
            leakdice
            libubootenv
            luaprompt
            neomutt
            neovim-unwrapped
            nix-direnv
            oelint-adv
            pandoc
            peda
            polybar
            qmarkdown
            sbkeys
            sscep
            vcalendar-filter
            zig
            zoxide
            ;

          zen_kernel = pkgs.linuxPackages_zen.kernel;

          sad = pkgs.callPackage ./pkgs/sad { inherit naersk-lib; };
          aoc-cli = pkgs.callPackage ./pkgs/aoc-cli { inherit naersk-lib; };
        };

        defaultPackage = pkgs.hello;

      }));
}
