# This file has been originally generated by ./pkgs/misc/vim-plugins/update.py.
# Now, it's updated using niv.

{ lib, buildVimPluginFrom2Nix, fetchFromGitHub }:

let sources = import ./nix/sources.nix; in

final: prev:
{
  ale = buildVimPluginFrom2Nix {
    pname = "ale";
    version = "2021-05-04";
    src = fetchFromGitHub (with sources.ale; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/dense-analysis/ale/";
  };

  barbar-nvim = buildVimPluginFrom2Nix {
    pname = "barbar-nvim";
    version = "2021-05-19";
    src = fetchFromGitHub (with sources.barbar-nvim; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/romgrk/barbar.nvim/";
  };

  detectindent = buildVimPluginFrom2Nix {
    pname = "detectindent";
    version = "2015-03-09";
    src = fetchFromGitHub (with sources.detectindent; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/ciaranm/detectindent/";
  };

  diffconflicts = buildVimPluginFrom2Nix {
    pname = "diffconflicts";
    version = "2020-12-08";
    src = fetchFromGitHub (with sources.diffconflicts; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/whiteinge/diffconflicts/";
  };

  editorconfig-vim = buildVimPluginFrom2Nix {
    pname = "editorconfig-vim";
    version = "2021-04-04";
    src = fetchFromGitHub (with sources.editorconfig-vim; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/editorconfig/editorconfig-vim/";
  };

  file-line = buildVimPluginFrom2Nix {
    pname = "file-line";
    version = "2012-03-07";
    src = fetchFromGitHub (with sources.file-line; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/vim-scripts/file-line/";
  };

  FixCursorHold-nvim = buildVimPluginFrom2Nix {
    pname = "FixCursorHold-nvim";
    version = "2021-04-16";
    src = fetchFromGitHub (with sources.FixCursorHold-nvim; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/antoinemadec/FixCursorHold.nvim/";
  };

  friendly-snippets = buildVimPluginFrom2Nix {
    pname = "friendly-snippets";
    version = "2021-05-20";
    src = fetchFromGitHub (with sources.friendly-snippets; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/rafamadriz/friendly-snippets/";
  };

  FTerm-nvim = buildVimPluginFrom2Nix {
    pname = "FTerm-nvim";
    version = "2021-04-24";
    src = fetchFromGitHub (with sources.FTerm-nvim; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/numtostr/FTerm.nvim/";
  };

  galaxyline-nvim = buildVimPluginFrom2Nix {
    pname = "galaxyline-nvim";
    version = "2021-04-25";
    src = fetchFromGitHub (with sources.galaxyline-nvim; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/glepnir/galaxyline.nvim/";
  };

  gina-vim = buildVimPluginFrom2Nix {
    pname = "gina-vim";
    version = "2021-04-28";
    src = fetchFromGitHub (with sources.gina-vim; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/lambdalisue/gina.vim/";
  };

  indent-guides-nvim = buildVimPluginFrom2Nix {
    pname = "indent-guides-nvim";
    version = "2021-03-26";
    src = fetchFromGitHub (with sources.indent-guides-nvim; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/glepnir/indent-guides.nvim/";
  };

  neoformat = buildVimPluginFrom2Nix {
    pname = "neoformat";
    version = "2021-04-20";
    src = fetchFromGitHub (with sources.neoformat; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/sbdchd/neoformat/";
  };

  nvim-colorizer-lua = buildVimPluginFrom2Nix {
    pname = "nvim-colorizer-lua";
    version = "2020-06-11";
    src = fetchFromGitHub (with sources.nvim-colorizer-lua; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/norcalli/nvim-colorizer.lua/";
  };

  nvim-compe = buildVimPluginFrom2Nix {
    pname = "nvim-compe";
    version = "2021-05-18";
    src = fetchFromGitHub (with sources.nvim-compe; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/hrsh7th/nvim-compe/";
  };

  nvim-lightbulb = buildVimPluginFrom2Nix {
    pname = "nvim-lightbulb";
    version = "2021-03-13";
    src = fetchFromGitHub (with sources.nvim-lightbulb; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/kosayoda/nvim-lightbulb/";
  };

  nvim-lspconfig = buildVimPluginFrom2Nix {
    pname = "nvim-lspconfig";
    version = "2021-05-19";
    src = fetchFromGitHub (with sources.nvim-lspconfig; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/neovim/nvim-lspconfig/";
  };

  nvim-peekup = buildVimPluginFrom2Nix {
    pname = "nvim-peekup";
    version = "2021-04-04";
    src = fetchFromGitHub (with sources.nvim-peekup; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/gennaro-tedesco/nvim-peekup/";
  };

  nvim-treesitter = buildVimPluginFrom2Nix {
    pname = "nvim-treesitter";
    version = "2021-05-19";
    src = fetchFromGitHub (with sources.nvim-treesitter; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/nvim-treesitter/nvim-treesitter/";
  };

  nvim-treesitter-refactor = buildVimPluginFrom2Nix {
    pname = "nvim-treesitter-refactor";
    version = "2021-05-03";
    src = fetchFromGitHub (with sources.nvim-treesitter-refactor; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/nvim-treesitter/nvim-treesitter-refactor/";
  };

  nvim-treesitter-textobjects = buildVimPluginFrom2Nix {
    pname = "nvim-treesitter-textobjects";
    version = "2021-05-11";
    src = fetchFromGitHub (with sources.nvim-treesitter-textobjects; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects/";
  };

  nvim-web-devicons = buildVimPluginFrom2Nix {
    pname = "nvim-web-devicons";
    version = "2021-05-19";
    src = fetchFromGitHub (with sources.nvim-web-devicons; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/kyazdani42/nvim-web-devicons/";
  };

  papercolor-theme = buildVimPluginFrom2Nix {
    pname = "papercolor-theme";
    version = "2020-12-04";
    src = fetchFromGitHub (with sources.papercolor-theme; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/NLKNguyen/papercolor-theme/";
  };

  plenary-nvim = buildVimPluginFrom2Nix {
    pname = "plenary-nvim";
    version = "2021-05-08";
    src = fetchFromGitHub (with sources.plenary-nvim; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/nvim-lua/plenary.nvim/";
  };

  popup-nvim = buildVimPluginFrom2Nix {
    pname = "popup-nvim";
    version = "2021-05-08";
    src = fetchFromGitHub (with sources.popup-nvim; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/nvim-lua/popup.nvim/";
  };

  rust-vim = buildVimPluginFrom2Nix {
    pname = "rust-vim";
    version = "2021-02-15";
    src = fetchFromGitHub (with sources.rust-vim; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/rust-lang/rust.vim/";
  };

  tabular = buildVimPluginFrom2Nix {
    pname = "tabular";
    version = "2019-02-19";
    src = fetchFromGitHub (with sources.tabular; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/godlygeek/tabular/";
  };

  telescope-nvim = buildVimPluginFrom2Nix {
    pname = "telescope-nvim";
    version = "2021-05-16";
    src = fetchFromGitHub (with sources.telescope-nvim; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/nvim-telescope/telescope.nvim/";
  };

  undotree = buildVimPluginFrom2Nix {
    pname = "undotree";
    version = "2021-05-16";
    src = fetchFromGitHub (with sources.undotree; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/mbbill/undotree/";
  };

  vim-better-whitespace = buildVimPluginFrom2Nix {
    pname = "vim-better-whitespace";
    version = "2020-03-24";
    src = fetchFromGitHub (with sources.vim-better-whitespace; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/ntpeters/vim-better-whitespace/";
  };

  vim-bitbake = buildVimPluginFrom2Nix {
    pname = "vim-bitbake";
    version = "2020-09-15";
    src = fetchFromGitHub (with sources.vim-bitbake; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/kergoth/vim-bitbake/";
  };

  vim-boxdraw = buildVimPluginFrom2Nix {
    pname = "vim-boxdraw";
    version = "2021-03-25";
    src = fetchFromGitHub (with sources.vim-boxdraw; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/michaeladler/vim-boxdraw/";
  };

  vim-commentary = buildVimPluginFrom2Nix {
    pname = "vim-commentary";
    version = "2021-03-23";
    src = fetchFromGitHub (with sources.vim-commentary; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/tpope/vim-commentary/";
  };

  vim-cool = buildVimPluginFrom2Nix {
    pname = "vim-cool";
    version = "2020-04-18";
    src = fetchFromGitHub (with sources.vim-cool; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/romainl/vim-cool/";
  };

  vim-dispatch = buildVimPluginFrom2Nix {
    pname = "vim-dispatch";
    version = "2021-04-17";
    src = fetchFromGitHub (with sources.vim-dispatch; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/tpope/vim-dispatch/";
  };

  vim-enmasse = buildVimPluginFrom2Nix {
    pname = "vim-enmasse";
    version = "2018-04-03";
    src = fetchFromGitHub (with sources.vim-enmasse; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/Olical/vim-enmasse/";
  };

  vim-go = buildVimPluginFrom2Nix {
    pname = "vim-go";
    version = "2021-05-17";
    src = fetchFromGitHub (with sources.vim-go; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/fatih/vim-go/";
  };

  vim-ingo-library = buildVimPluginFrom2Nix {
    pname = "vim-ingo-library";
    version = "2021-03-22";
    src = fetchFromGitHub (with sources.vim-ingo-library; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/inkarkat/vim-ingo-library/";
  };

  vim-json = buildVimPluginFrom2Nix {
    pname = "vim-json";
    version = "2018-01-10";
    src = fetchFromGitHub (with sources.vim-json; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/elzr/vim-json/";
  };

  vim-lastplace = buildVimPluginFrom2Nix {
    pname = "vim-lastplace";
    version = "2021-03-29";
    src = fetchFromGitHub (with sources.vim-lastplace; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/farmergreg/vim-lastplace/";
  };

  vim-markdown = buildVimPluginFrom2Nix {
    pname = "vim-markdown";
    version = "2020-07-14";
    src = fetchFromGitHub (with sources.vim-markdown; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/plasticboy/vim-markdown/";
  };

  vim-nix = buildVimPluginFrom2Nix {
    pname = "vim-nix";
    version = "2020-11-16";
    src = fetchFromGitHub (with sources.vim-nix; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/LnL7/vim-nix/";
  };

  vim-obsession = buildVimPluginFrom2Nix {
    pname = "vim-obsession";
    version = "2021-03-22";
    src = fetchFromGitHub (with sources.vim-obsession; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/tpope/vim-obsession/";
  };

  vim-pandoc = buildVimPluginFrom2Nix {
    pname = "vim-pandoc";
    version = "2021-04-30";
    src = fetchFromGitHub (with sources.vim-pandoc; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/vim-pandoc/vim-pandoc/";
  };

  vim-pandoc-syntax = buildVimPluginFrom2Nix {
    pname = "vim-pandoc-syntax";
    version = "2021-03-10";
    src = fetchFromGitHub (with sources.vim-pandoc-syntax; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/vim-pandoc/vim-pandoc-syntax/";
  };

  vim-prosession = buildVimPluginFrom2Nix {
    pname = "vim-prosession";
    version = "2021-03-21";
    src = fetchFromGitHub (with sources.vim-prosession; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/dhruvasagar/vim-prosession/";
  };

  vim-repeat = buildVimPluginFrom2Nix {
    pname = "vim-repeat";
    version = "2021-01-25";
    src = fetchFromGitHub (with sources.vim-repeat; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/tpope/vim-repeat/";
  };

  vim-sensible = buildVimPluginFrom2Nix {
    pname = "vim-sensible";
    version = "2019-11-24";
    src = fetchFromGitHub (with sources.vim-sensible; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/tpope/vim-sensible/";
  };

  vim-sneak = buildVimPluginFrom2Nix {
    pname = "vim-sneak";
    version = "2020-09-01";
    src = fetchFromGitHub (with sources.vim-sneak; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/justinmk/vim-sneak/";
  };

  vim-SpellCheck = buildVimPluginFrom2Nix {
    pname = "vim-SpellCheck";
    version = "2020-08-18";
    src = fetchFromGitHub (with sources.vim-SpellCheck; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/inkarkat/vim-SpellCheck/";
  };

  vim-spellsync = buildVimPluginFrom2Nix {
    pname = "vim-spellsync";
    version = "2018-09-18";
    src = fetchFromGitHub (with sources.vim-spellsync; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/micarmst/vim-spellsync/";
  };

  vim-startuptime = buildVimPluginFrom2Nix {
    pname = "vim-startuptime";
    version = "2021-05-04";
    src = fetchFromGitHub (with sources.vim-startuptime; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/dstein64/vim-startuptime/";
  };

  vim-surround = buildVimPluginFrom2Nix {
    pname = "vim-surround";
    version = "2019-11-28";
    src = fetchFromGitHub (with sources.vim-surround; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/tpope/vim-surround/";
  };

  vim-tmux-navigator = buildVimPluginFrom2Nix {
    pname = "vim-tmux-navigator";
    version = "2020-11-12";
    src = fetchFromGitHub (with sources.vim-tmux-navigator; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/christoomey/vim-tmux-navigator/";
  };

  vim-toml = buildVimPluginFrom2Nix {
    pname = "vim-toml";
    version = "2020-12-08";
    src = fetchFromGitHub (with sources.vim-toml; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/cespare/vim-toml/";
  };

  vim-vinegar = buildVimPluginFrom2Nix {
    pname = "vim-vinegar";
    version = "2021-03-16";
    src = fetchFromGitHub (with sources.vim-vinegar; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/tpope/vim-vinegar/";
  };

  vim-vsnip = buildVimPluginFrom2Nix {
    pname = "vim-vsnip";
    version = "2021-04-21";
    src = fetchFromGitHub (with sources.vim-vsnip; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/hrsh7th/vim-vsnip/";
  };

  vim-which-key = buildVimPluginFrom2Nix {
    pname = "vim-which-key";
    version = "2021-05-04";
    src = fetchFromGitHub (with sources.vim-which-key; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/liuchengxu/vim-which-key/";
  };

  zig-vim = buildVimPluginFrom2Nix {
    pname = "zig-vim";
    version = "2021-05-12";
    src = fetchFromGitHub (with sources.zig-vim; { inherit owner repo rev sha256; });
    meta.homepage = "https://github.com/ziglang/zig.vim/";
  };

}
