# This file has been originally generated by ./pkgs/misc/vim-plugins/update.py.

{ sources, lib, buildVimPluginFrom2Nix, fetchFromGitHub }:

final: prev:
{
  ale =  buildVimPluginFrom2Nix (let src = sources.ale-src; in {
    pname = "ale";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/dense-analysis/ale/";
  });

  barbar-nvim =  buildVimPluginFrom2Nix (let src = sources.barbar-nvim-src; in {
    pname = "barbar-nvim";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/romgrk/barbar.nvim/";
  });

  detectindent =  buildVimPluginFrom2Nix (let src = sources.detectindent-src; in {
    pname = "detectindent";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/ciaranm/detectindent/";
  });

  diffconflicts =  buildVimPluginFrom2Nix (let src = sources.diffconflicts-src; in {
    pname = "diffconflicts";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/whiteinge/diffconflicts/";
  });

  editorconfig-vim =  buildVimPluginFrom2Nix (let src = sources.editorconfig-vim-src; in {
    pname = "editorconfig-vim";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/editorconfig/editorconfig-vim/";
  });

  file-line =  buildVimPluginFrom2Nix (let src = sources.file-line-src; in {
    pname = "file-line";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/vim-scripts/file-line/";
  });

  FixCursorHold-nvim =  buildVimPluginFrom2Nix (let src = sources.FixCursorHold-nvim-src; in {
    pname = "FixCursorHold-nvim";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/antoinemadec/FixCursorHold.nvim/";
  });

  friendly-snippets =  buildVimPluginFrom2Nix (let src = sources.friendly-snippets-src; in {
    pname = "friendly-snippets";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/rafamadriz/friendly-snippets/";
  });

  FTerm-nvim =  buildVimPluginFrom2Nix (let src = sources.FTerm-nvim-src; in {
    pname = "FTerm-nvim";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/numtostr/FTerm.nvim/";
  });

  galaxyline-nvim =  buildVimPluginFrom2Nix (let src = sources.galaxyline-nvim-src; in {
    pname = "galaxyline-nvim";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/glepnir/galaxyline.nvim/";
  });

  gina-vim =  buildVimPluginFrom2Nix (let src = sources.gina-vim-src; in {
    pname = "gina-vim";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/lambdalisue/gina.vim/";
  });

  indent-guides-nvim =  buildVimPluginFrom2Nix (let src = sources.indent-guides-nvim-src; in {
    pname = "indent-guides-nvim";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/glepnir/indent-guides.nvim/";
  });

  neoformat =  buildVimPluginFrom2Nix (let src = sources.neoformat-src; in {
    pname = "neoformat";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/sbdchd/neoformat/";
  });

  nvim-colorizer-lua =  buildVimPluginFrom2Nix (let src = sources.nvim-colorizer-lua-src; in {
    pname = "nvim-colorizer-lua";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/norcalli/nvim-colorizer.lua/";
  });

  nvim-compe =  buildVimPluginFrom2Nix (let src = sources.nvim-compe-src; in {
    pname = "nvim-compe";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/hrsh7th/nvim-compe/";
  });

  completion-buffers = buildVimPluginFrom2Nix (let src = sources.completion-buffers-src; in {
    pname = "completion-buffers";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/steelso/completion-buffers";
  });

  completion-nvim =  buildVimPluginFrom2Nix (let src = sources.completion-nvim-src; in {
    pname = "completion-nvim";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/nvim-lua/completion-nvim";
  });

  nvim-lightbulb =  buildVimPluginFrom2Nix (let src = sources.nvim-lightbulb-src; in {
    pname = "nvim-lightbulb";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/kosayoda/nvim-lightbulb/";
  });

  nvim-lspconfig =  buildVimPluginFrom2Nix (let src = sources.nvim-lspconfig-src; in {
    pname = "nvim-lspconfig";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/neovim/nvim-lspconfig/";
  });

  nvim-peekup =  buildVimPluginFrom2Nix (let src = sources.nvim-peekup-src; in {
    pname = "nvim-peekup";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/gennaro-tedesco/nvim-peekup/";
  });

  nvim-treesitter =  buildVimPluginFrom2Nix (let src = sources.nvim-treesitter-src; in {
    pname = "nvim-treesitter";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/nvim-treesitter/nvim-treesitter/";
  });

  nvim-treesitter-refactor =  buildVimPluginFrom2Nix (let src = sources.nvim-treesitter-refactor-src; in {
    pname = "nvim-treesitter-refactor";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/nvim-treesitter/nvim-treesitter-refactor/";
  });

  nvim-treesitter-textobjects =  buildVimPluginFrom2Nix (let src = sources.nvim-treesitter-textobjects-src; in {
    pname = "nvim-treesitter-textobjects";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects/";
  });

  nvim-web-devicons =  buildVimPluginFrom2Nix (let src = sources.nvim-web-devicons-src; in {
    pname = "nvim-web-devicons";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/kyazdani42/nvim-web-devicons/";
  });

  papercolor-theme =  buildVimPluginFrom2Nix (let src = sources.papercolor-theme-src; in {
    pname = "papercolor-theme";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/NLKNguyen/papercolor-theme/";
  });

  plenary-nvim =  buildVimPluginFrom2Nix (let src = sources.plenary-nvim-src; in {
    pname = "plenary-nvim";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/nvim-lua/plenary.nvim/";
  });

  popup-nvim =  buildVimPluginFrom2Nix (let src = sources.popup-nvim-src; in {
    pname = "popup-nvim";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/nvim-lua/popup.nvim/";
  });

  rust-vim =  buildVimPluginFrom2Nix (let src = sources.rust-vim-src; in {
    pname = "rust-vim";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/rust-lang/rust.vim/";
  });

  tabular =  buildVimPluginFrom2Nix (let src = sources.tabular-src; in {
    pname = "tabular";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/godlygeek/tabular/";
  });

  telescope-nvim =  buildVimPluginFrom2Nix (let src = sources.telescope-nvim-src; in {
    pname = "telescope-nvim";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/nvim-telescope/telescope.nvim/";
  });

  undotree =  buildVimPluginFrom2Nix (let src = sources.undotree-src; in {
    pname = "undotree";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/mbbill/undotree/";
  });

  vim-better-whitespace =  buildVimPluginFrom2Nix (let src = sources.vim-better-whitespace-src; in {
    pname = "vim-better-whitespace";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/ntpeters/vim-better-whitespace/";
  });

  vim-bitbake =  buildVimPluginFrom2Nix (let src = sources.vim-bitbake-src; in {
    pname = "vim-bitbake";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/kergoth/vim-bitbake/";
  });

  vim-boxdraw =  buildVimPluginFrom2Nix (let src = sources.vim-boxdraw-src; in {
    pname = "vim-boxdraw";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/michaeladler/vim-boxdraw/";
  });

  vim-commentary =  buildVimPluginFrom2Nix (let src = sources.vim-commentary-src; in {
    pname = "vim-commentary";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/tpope/vim-commentary/";
  });

  vim-cool =  buildVimPluginFrom2Nix (let src = sources.vim-cool-src; in {
    pname = "vim-cool";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/romainl/vim-cool/";
  });

  vim-dispatch =  buildVimPluginFrom2Nix (let src = sources.vim-dispatch-src; in {
    pname = "vim-dispatch";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/tpope/vim-dispatch/";
  });

  vim-enmasse =  buildVimPluginFrom2Nix (let src = sources.vim-enmasse-src; in {
    pname = "vim-enmasse";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/Olical/vim-enmasse/";
  });

  vim-go =  buildVimPluginFrom2Nix (let src = sources.vim-go-src; in {
    pname = "vim-go";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/fatih/vim-go/";
  });

  vim-ingo-library =  buildVimPluginFrom2Nix (let src = sources.vim-ingo-library-src; in {
    pname = "vim-ingo-library";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/inkarkat/vim-ingo-library/";
  });

  vim-json =  buildVimPluginFrom2Nix (let src = sources.vim-json-src; in {
    pname = "vim-json";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/elzr/vim-json/";
  });

  vim-lastplace =  buildVimPluginFrom2Nix (let src = sources.vim-lastplace-src; in {
    pname = "vim-lastplace";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/farmergreg/vim-lastplace/";
  });

  vim-markdown =  buildVimPluginFrom2Nix (let src = sources.vim-markdown-src; in {
    pname = "vim-markdown";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/plasticboy/vim-markdown/";
  });

  vim-nix =  buildVimPluginFrom2Nix (let src = sources.vim-nix-src; in {
    pname = "vim-nix";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/LnL7/vim-nix/";
  });

  vim-obsession =  buildVimPluginFrom2Nix (let src = sources.vim-obsession-src; in {
    pname = "vim-obsession";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/tpope/vim-obsession/";
  });

  vim-pandoc =  buildVimPluginFrom2Nix (let src = sources.vim-pandoc-src; in {
    pname = "vim-pandoc";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/vim-pandoc/vim-pandoc/";
  });

  vim-pandoc-syntax =  buildVimPluginFrom2Nix (let src = sources.vim-pandoc-syntax-src; in {
    pname = "vim-pandoc-syntax";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/vim-pandoc/vim-pandoc-syntax/";
  });

  vim-prosession =  buildVimPluginFrom2Nix (let src = sources.vim-prosession-src; in {
    pname = "vim-prosession";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/dhruvasagar/vim-prosession/";
  });

  vim-repeat =  buildVimPluginFrom2Nix (let src = sources.vim-repeat-src; in {
    pname = "vim-repeat";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/tpope/vim-repeat/";
  });

  vim-sensible =  buildVimPluginFrom2Nix (let src = sources.vim-sensible-src; in {
    pname = "vim-sensible";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/tpope/vim-sensible/";
  });

  vim-sneak =  buildVimPluginFrom2Nix (let src = sources.vim-sneak-src; in {
    pname = "vim-sneak";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/justinmk/vim-sneak/";
  });

  vim-SpellCheck =  buildVimPluginFrom2Nix (let src = sources.vim-SpellCheck-src; in {
    pname = "vim-SpellCheck";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/inkarkat/vim-SpellCheck/";
  });

  vim-spellsync =  buildVimPluginFrom2Nix (let src = sources.vim-spellsync-src; in {
    pname = "vim-spellsync";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/micarmst/vim-spellsync/";
  });

  vim-startuptime =  buildVimPluginFrom2Nix (let src = sources.vim-startuptime-src; in {
    pname = "vim-startuptime";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/dstein64/vim-startuptime/";
  });

  vim-surround =  buildVimPluginFrom2Nix (let src = sources.vim-surround-src; in {
    pname = "vim-surround";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/tpope/vim-surround/";
  });

  vim-tmux-navigator =  buildVimPluginFrom2Nix (let src = sources.vim-tmux-navigator-src; in {
    pname = "vim-tmux-navigator";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/christoomey/vim-tmux-navigator/";
  });

  vim-toml =  buildVimPluginFrom2Nix (let src = sources.vim-toml-src; in {
    pname = "vim-toml";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/cespare/vim-toml/";
  });

  vim-vinegar =  buildVimPluginFrom2Nix (let src = sources.vim-vinegar-src; in {
    pname = "vim-vinegar";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/tpope/vim-vinegar/";
  });

  vim-vsnip =  buildVimPluginFrom2Nix (let src = sources.vim-vsnip-src; in {
    pname = "vim-vsnip";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/hrsh7th/vim-vsnip/";
  });

  vim-which-key =  buildVimPluginFrom2Nix (let src = sources.vim-which-key-src; in {
    pname = "vim-which-key";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/liuchengxu/vim-which-key/";
  });

  zig-vim =  buildVimPluginFrom2Nix (let src = sources.zig-vim-src; in {
    pname = "zig-vim";
    inherit src;
    version = toString src.lastModifiedDate;
    meta.homepage = "https://github.com/ziglang/zig.vim/";
  });

}
