name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: michaeladler
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: |
            ./result
            ./result-1
            ./result-2
            ./result-3
            ./result-4
            ./result-5
            ./result-6
            ./result-7
            ./result-8
            ./result-9
            ./result-10
            ./result-11
            ./result-12
            ./result-13

      - name: build
        run: |
          nix-shell \
            --command "just packagelist build-all" \
            -p nixVersions.latest just

      - name: Commit & Push changes
        uses: benkaiser/rebase-commit-push@v1.3
        with:
          message: "chore: update package list"
          rebase: true
