name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: nur-packages
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: build
        run: ./.ci/build.sh
      - name: push
        run: git push "https://$GITHUB_TOKEN@github.com/michaeladler/nur-packages" HEAD:master
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'

