name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: nur-packages
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: build
        run: .ci/build-all.sh
        env:
          GIT_AUTHOR_NAME: "Github Actions"
          GIT_AUTHOR_EMAIL: "actions@github"
          GIT_COMMITTER_NAME: "Github Actions"
          GIT_COMMITTER_EMAIL: "actions@github"

      - name: push
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git remote set-url origin "https://$GITHUB_TOKEN@github.com/michaeladler/nur-packages"
          git fetch origin master && git rebase origin/master
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'
