---
name: update-linux-lqx

on:
  workflow_dispatch:
  schedule:
    # NB: jobs may be delayed a couple of hours
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: nur-packages
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: update
        run: bash -x ./pkgs/linux-lqx/update.sh

      - name: build
        run: |
          nix-shell \
            --command "just build-lqx" \
            -p nixUnstable nix-build-uncached just

      - name: Commit & Push changes
        uses: benkaiser/rebase-commit-push@v1.1
        with:
          message: 'chore: update linux-lqx'
          rebase: true
