name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V28
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v15
        with:
          name: michaeladler
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: build
        run: |
          nix-shell \
            --command "just packagelist build-all" \
            -p nixVersions.latest just

      - name: Commit & Push changes
        uses: benkaiser/rebase-commit-push@v1.3
        with:
          message: "chore: update package list"
          rebase: true
