---
name: lqx

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: nur-packages
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: build
        run: |
          nix-shell \
            --command "just build-lqx" \
            -p nixUnstable just

      - name: Commit & Push changes
        uses: benkaiser/rebase-commit-push@v1.1
        with:
          message: 'chore: update package list'
          rebase: true
