name: zen

on:
  push:
  workflow_dispatch:
  schedule:
    # NB: jobs may be delayed a couple of hours
    - cron:  '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: nur-packages
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: build
        run: |
          nix-shell \
            --command "make build-zen" \
            -p nixUnstable just

      - name: Commit & Push changes
        uses: benkaiser/rebase-commit-push@v1.1
        with:
          message: 'chore: update package list'
          rebase: true
