name: Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: nur-packages
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: build
        run: |
          nix-shell \
            --command "make build-kernel" \
            -p nixUnstable
