name: Update World

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    # NB: jobs may be delayed a couple of hours
    - cron:  '0 0 * * *'

jobs:

  update-all:
    runs-on: ubuntu-latest

    steps:

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 10000
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: nur-packages
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: update
        run: |
          mkdir -p ~/.config/nix ~/.config/nixpkgs/overlays
          [ -n "${GITHUB_TOKEN:-}" ] || {
            echo "GITHUB_TOKEN not set"
            exit 1
          }
          echo "access-tokens = github.com=$GITHUB_TOKEN" >>~/.config/nix/nix.conf

          nix-shell \
            --command "make -j update-all" \
            -p nixUnstable update-nix-fetchgit
          nix-shell \
            --command "nix --experimental-features 'nix-command flakes' flake check" \
            -p nixUnstable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: |
          nix-shell \
            --command "make build-all" \
            -p nixUnstable

      - name: Commit & Push changes
        uses: benkaiser/rebase-commit-push@v1.1
        with:
          message: 'chore: update packages'
          rebase: true
