name: update

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    # NB: jobs may be delayed a couple of hours
    - cron: "0 0 * * *"

jobs:
  update-all:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 40000
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: nur-packages
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix run 'nixpkgs#just' -- update-all

      - name: build
        run: |
          nix-shell \
            --command "just build-all build-zen" \
            -p nixUnstable nix-build-uncached just

      - name: Commit & Push changes
        uses: benkaiser/rebase-commit-push@v1.3
        with:
          message: "chore: update packages"
          rebase: true
