name: update zig

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    # NB: jobs may be delayed a couple of hours
    - cron:  '0 0 * * *'

jobs:

  update-zig:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: nur-packages
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: update
        run: |
          nix-shell \
            --command "make update-zig" \
            -p nixUnstable update-nix-fetchgit

      - name: build
        run: |
          timeout -s 9 5m \
            nix-shell \
              --command "nix --experimental-features 'nix-command flakes' build -L --no-link '.#zig-master' '.#zls'" \
              -p nixUnstable

      - name: Commit & Push changes
        uses: benkaiser/rebase-commit-push@v1.1
        with:
          message: 'chore: update zig and zls'
          rebase: true
