name: update

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    # NB: jobs may be delayed a couple of hours
    - cron: "0 0 * * *"

jobs:
  update-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        with:
          name: michaeladler
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: update and build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix-shell \
            --command "just update-all build-all" \
            -p nixVersions.latest just nix-update

      - name: Commit & Push changes
        uses: benkaiser/rebase-commit-push@v1.3
        with:
          message: "chore: update packages"
          rebase: true
