name: Update

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    # NB: jobs may be delayed a couple of hours
    - cron:  '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: nur-packages
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: update
        run: ./.ci/update.sh
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'

      - name: build
        run: ./.ci/build.sh

      - name: push
        run: git push "https://$GITHUB_TOKEN@github.com/michaeladler/nur-packages" HEAD:master
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'

