name: Update World

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    # NB: jobs may be delayed a couple of hours
    - cron:  '0 0 * * *'

jobs:

  update-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: nur-packages
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: update
        run: |
          mkdir -p ~/.config/nix ~/.config/nixpkgs/overlays
          echo "access-tokens = github.com=$GITHUB_TOKEN" >>~/.config/nix/nix.conf

          nix-shell \
            --command "make -j8 update-flakes update-firefox-addons update-firefox update-chromium update-brave update-rust-pkgs update-other" \
            -p nixUnstable update-nix-fetchgit
          nix-shell \
            --command "nix --experimental-features 'nix-command flakes' flake check" \
            -p nixUnstable
          git diff --exit-code || git commit -am 'chore: update packages'
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'
          GIT_AUTHOR_NAME: "Github Actions"
          GIT_AUTHOR_EMAIL: "actions@github"
          GIT_COMMITTER_NAME: "Github Actions"
          GIT_COMMITTER_EMAIL: "actions@github"

      - name: build
        run: |
          nix-shell \
            --command "make build-all" \
            -p nixUnstable

      - name: push
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git remote set-url origin "https://$GITHUB_TOKEN@github.com/michaeladler/nur-packages"
          git fetch origin master && git rebase origin/master
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'
          GIT_AUTHOR_NAME: "Github Actions"
          GIT_AUTHOR_EMAIL: "actions@github"
          GIT_COMMITTER_NAME: "Github Actions"
          GIT_COMMITTER_EMAIL: "actions@github"

  update-zig:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: nur-packages
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: update
        run: |
          nix-shell \
            --command "make -j2 update-zig update-zls" \
            -p nixUnstable update-nix-fetchgit
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'
          GIT_AUTHOR_NAME: "Github Actions"
          GIT_AUTHOR_EMAIL: "actions@github"
          GIT_COMMITTER_NAME: "Github Actions"
          GIT_COMMITTER_EMAIL: "actions@github"

      - name: build
        run: |
          nix-shell \
            --command "nix --experimental-features 'nix-command flakes' build --no-link '.#zig' '.#zls'" \
            -p nixUnstable
          git diff --exit-code || git commit -am 'chore: update zig and zls'

      - name: push
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git remote set-url origin "https://$GITHUB_TOKEN@github.com/michaeladler/nur-packages"
          git fetch origin master && git rebase origin/master
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'
          GIT_AUTHOR_NAME: "Github Actions"
          GIT_AUTHOR_EMAIL: "actions@github"
          GIT_COMMITTER_NAME: "Github Actions"
          GIT_COMMITTER_EMAIL: "actions@github"

