name: Update World

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    # NB: jobs may be delayed a couple of hours
    - cron:  '0 0 * * *'

jobs:

  update-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: nur-packages
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: update
        run: |
          mkdir -p ~/.config/nix
          printf "access-tokens = github.com=%s" "$GITHUB_TOKEN" >>~/.config/nix/nix.conf
          .ci/update-all.sh
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'
          GIT_AUTHOR_NAME: "Github Actions"
          GIT_AUTHOR_EMAIL: "actions@github"
          GIT_COMMITTER_NAME: "Github Actions"
          GIT_COMMITTER_EMAIL: "actions@github"

      - name: build
        run: .ci/build-all.sh

      - name: push
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git remote set-url origin "https://$GITHUB_TOKEN@github.com/michaeladler/nur-packages"
          git fetch origin master && git rebase origin/master
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'

  update-zig:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: nur-packages
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: update
        run: .ci/update-zig.sh
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'
          GIT_AUTHOR_NAME: "Github Actions"
          GIT_AUTHOR_EMAIL: "actions@github"
          GIT_COMMITTER_NAME: "Github Actions"
          GIT_COMMITTER_EMAIL: "actions@github"

      - name: build
        run: .ci/build-zig.sh

      - name: push
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git remote set-url origin "https://$GITHUB_TOKEN@github.com/michaeladler/nur-packages"
          git fetch origin master && git rebase origin/master
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'
