name: Update Workflow

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 5 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install nix
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      # Run my update script
      - name: update nur / nur-combined
        run: ./.ci/update.sh
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'
